name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment with caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install newman and reporter locally
      - name: Install Newman and Reporter
        run: |
          npm install newman newman-reporter-htmlextra

      # Run Newman collection
      - name: Run POSTMAN collection
        run: |
          npx newman run ./store.postman_collection.json \
            --reporters htmlextra \
            --reporter-htmlextra-export ./testResults/htmlreport.html \
            --reporter-htmlextra-darkTheme
        continue-on-error: false

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: ./testResults
